pipeline {

  agent any
  
  stages {
    stage('Install dependencies') {
      steps { sh 'npm install' }
    }
    stage('Code quality') {
        steps { sh 'npm run-script lint -- --fix' }
    }
    stage('Unit tests') {
        steps { sh 'npm run-script test -- --watch false --browsers=ChromeHeadless' }
    }
    stage('End to end tests') {
        steps { sh 'npm run-script e2e' }
    }
    stage('Build') {
      steps { sh 'npm run-script build -- --prod' }
    }
    stage('Compresss') {
      steps {
        sh 'cd ./dist' 
        sh 'tar -zcvf team-builder-tool-archive.tar.gz team-builder-tool'
      }
    }
    stage('Remote deployment') {
      steps {
        withCredentials([sshUserPrivateKey(credentialsId: '0356a688-d313-49c9-919e-227b95f1f068', keyFileVariable: 'keyFile', passphraseVariable: '', usernameVariable: 'username')]) {
          sh 'scp -v -i $keyFile team-builder-tool-archive.tar.gz ubuntu@15.236.247.12:/home/apps'
          sh 'ssh -v ubuntu@15.236.247.12'
          sh 'cd /home/apps'
          sh 'tar -zxvf team-builder-tool-archive.tar.gz'
          sh 'exit'
        }
      }
    }
  }
}