pipeline {

  agent any
  
  stages {
    stage('Install dependencies') {
      steps { sh 'npm install' }
    }
    stage('Code quality') {
        steps { sh 'npm run-script lint -- --fix' }
    }
    stage('Unit tests') {
        steps { sh 'npm run-script test -- --watch false --browsers=ChromeHeadless' }
    }
    stage('End to end tests') {
        steps { sh 'npm run-script e2e -- --protractor-config e2e/protractor.conf.prod.js' }
    }
    stage('Build artefact') {
      steps { sh 'npm run-script build -- --configuration production' }
    }
    stage('Artefact compression') {
      steps {
        sh 'tar -C ./dist -zcvf ./dist/team-builder-tool-archive.tar.gz team-builder-tool'
      }
    }
    stage('Remote deployment') {
      steps {
        script {
          def remote = [:]
          remote.name = 'main_server'
          remote.host = "${AWS_LIGTHSAIL_SERVER_IP}"
          remote.allowAnyHosts = true
          withCredentials([sshUserPrivateKey(credentialsId: '0356a688-d313-49c9-919e-227b95f1f068', keyFileVariable: 'keyFile', passphraseVariable: '', usernameVariable: 'username')]) {
            remote.user = username
            remote.identityFile = keyFile
            sh 'scp -i $keyFile ./dist/team-builder-tool-archive.tar.gz ubuntu@${AWS_LIGTHSAIL_SERVER_IP}:/home/apps'
            sshCommand remote: remote, command: 'cd /home/apps && sudo rm -r team-builder-tool/* && sudo tar -zxvf team-builder-tool-archive.tar.gz && sudo chmod -R 765 team-builder-tool && sudo chown -R ubuntu:ubuntu team-builder-tool && sudo rm team-builder-tool-archive.tar.gz'
          }
        }
      }
    }
  }
}