/**
 * Player field position enum
 */
export enum PlayerFieldPositionEnum {
	BATTER = 'BATTER',
	PITCHER = 'PITCHER',
	RUNNER = 'RUNNER',
	CATCHER = 'CATCHER',
	FIRST_BASEMAN = 'FIRST_BASEMAN',
	SECOND_BASEMAN = 'SECOND_BASEMAN',
	THIRD_BASEMAN = 'THIRD_BASEMAN',
	SHORT_STOP = 'SHORT_STOP',
	LEFT_FIELDER = 'LEFT_FIELDER',
	CENTER_FIELDER = 'CENTER_FIELDER',
	RIGHT_FIELDER = 'RIGHT_FIELDER',
	UNKNOWN = 'UNKNOWN'
}
